Feature/signup test
wolox-training/dce-react pull request #3
Opened 2020-10-26 15:56 UTC by diego317

## Summary

- add router

- add login screen

- add testcases

- add public layout component

## Screenshots

![login](https://user-images.githubusercontent.com/39997928/97195922-dc556e00-1779-11eb-94fc-2607fc15156a.gif)

## Trello Card

https://trello.com/c/CWqGvVQE/94-login

https://trello.com/c/m3DYrg5U/117-tests-de-sign-up

2020-10-26 20:55 UTC, alejobh requested changes
Really nice work!

2020-10-26 20:55 UTC, alejobh commented on src/app/components/PublicLayout/index.js
> +export default function PublicLayout({ children }) {
`PublicLayoutWrapper`

2020-10-26 20:55 UTC, alejobh commented on src/app/components/PublicLayout/index.js
> +  return <div className={styles.publicLayout}>{children}</div>;
`styles.container`

2020-10-26 20:55 UTC, alejobh commented on src/app/index.js
> +      <Suspense fallback={<div> Loading </div>}>
Use your current Loader component

2020-10-26 20:55 UTC, alejobh commented on src/app/hooks/useAPI.js
> +            type: result.status === success ? FETCH_ACTIONS.success : FETCH_ACTIONS.error,
use apiSauce `ok:true|false` to work with this

2020-10-26 20:55 UTC, alejobh commented on src/app/components/TextField/index.test.js
> +
you have missing test case: input error

2020-10-26 20:55 UTC, alejobh commented on src/app/screens/Login/index.js
> +import wolox from '../../assets/logos/wolox.png';
absolute route

2020-10-26 20:55 UTC, alejobh commented on src/app/screens/Login/index.js
> +import wolox from '../../assets/logos/wolox.png';
@DavidRojas1612 help with the jest config for absolute routes

2020-10-26 20:55 UTC, alejobh commented on src/app/screens/Login/index.js
> +import wolox from '../../assets/logos/wolox.png';
```
"~assets(.*)": "<rootDir>/src/app/assets/$1",
```

2020-10-26 20:55 UTC, alejobh commented on src/app/screens/Login/index.js
> +        console.log('se logueo con exito', response);
add TODO and `eslint-disable-next-line no-console`

2020-10-26 20:55 UTC, alejobh commented on src/app/screens/Login/index.js
> +  };
```
doFetch({ data: {session: data} })
```

2020-10-26 20:55 UTC, alejobh commented on src/app/screens/SignUp/components/Form/index.js
> +        data-testid="email"
use constants, same for Login

2020-10-26 20:55 UTC, alejobh commented on src/app/screens/SignUp/components/Form/index.js
> +        data-testid="password"
saame

2020-10-26 20:55 UTC, alejobh commented on src/app/screens/SignUp/components/Form/index.js
> +        data-testid="confirmPassword"
same

2020-10-26 20:55 UTC, alejobh commented on src/app/screens/SignUp/index.js
> +        }}
```
 onClick={handlePushLogin}
```

2020-10-26 20:55 UTC, alejobh commented on src/app/screens/SignUp/index.js
> +        history.push('/login');
`handlePushLogin()`

2020-10-26 20:55 UTC, alejobh commented on src/app/screens/SignUp/index.js
> +
```
const handlePushLogin = useCallback(()=>{
  history.push(ROUTES.login);
}, [history])
```

2020-10-26 20:55 UTC, alejobh commented on src/app/screens/SignUp/index.js
> +    if (Object.keys(response).length > 0) {
response should be initially `null`, so just need to check `if(response)`

2020-10-26 20:55 UTC, alejobh commented on src/constants/api.js
>  export const REST_METHODS = ['GET', 'HEAD', 'DELETE', 'LINK', 'UNLINK', 'POST', 'PUT', 'PATCH'];
i think this is exported by `apiSuace` but im. not. 100% sure

2020-10-27 23:31 UTC, alejobh reviewed
The last comments and we are ok!

2020-10-27 23:31 UTC, alejobh commented on src/app/components/PublicLayoutWrapper/index.js
> +export default function PublicLayout({ children }) {
`export default function PublicLayoutWrapper({ children }) {`

remember that this will be the suggested name by the IDLE

2020-10-27 23:31 UTC, alejobh commented on src/app/screens/Login/index.js
> +        addToast(response, { appearance: 'error' });
sorry for this, but could yo extract the. appearances in an object global constant?

```
addToast(response, TOAST_TYPES.error);
```

2020-10-27 23:31 UTC, alejobh commented on src/app/screens/Login/index.js
> +  };
same comment

2020-10-28 16:45 UTC, alejobh commented on src/app/screens/Login/index.js
> +    null
for the next PR: you dont need to do this is your `initialData` in your useAPI hook would be default null

2020-10-28 16:46 UTC, alejobh approved these changes

2020-10-28 20:30 UTC, DavidRojas1612 approved these changes
🎉  Amazing work!!!

2020-10-28 20:30 UTC, DavidRojas1612 commented on .env.development
> +REACT_APP_BACKEND_URL = 'https://private-anon-3d5bee2ac8-wbooksapi.apiary-mock.com/api/v1'
add eof

2020-10-28 20:51 UTC, merged